# Generated by Django 3.0.5 on 2020-05-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewdatabd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crewdatabd.District'),
        ),
        migrations.AlterField(
            model_name='companie',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crewdatabd.Thana'),
        ),
        migrations.AlterField(
            model_name='ghatlabor',
            name='address_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crewdatabd.District'),
        ),
        migrations.AlterField(
            model_name='ghatlabor',
            name='address_thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crewdatabd.Thana'),
        ),
        migrations.AlterField(
            model_name='shippingstaff',
            name='contact_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='shippingstaff',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crewdatabd.District'),
        ),
        migrations.AlterField(
            model_name='shippingstaff',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crewdatabd.EducationLevel'),
        ),
        migrations.AlterField(
            model_name='shippingstaff',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crewdatabd.Thana'),
        ),
    ]
