# Generated by Django 3.0.5 on 2020-05-18 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crewdatabd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=200, verbose_name='Sector')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalStakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Labor Name')),
                ('org_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Labor Position')),
                ('contact_1', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Contact No 1')),
                ('contact_2', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Contact No 2')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note')),
                ('social_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Social URL')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added Date')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated On')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crewdatabd.StakeholderSector')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
