# Generated by Django 3.0.5 on 2020-05-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewdatabd', '0002_externalstakeholder_stakeholdersector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalstakeholder',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='externalstakeholder',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='externalstakeholder',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crewdatabd.StakeholderSector'),
        ),
    ]
