# Generated by Django 3.0.5 on 2020-05-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdatabd', '0003_auto_20200518_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalstakeholder',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Department'),
        ),
    ]
