# Generated by Django 3.0.5 on 2020-05-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdatabd', '0004_externalstakeholder_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='ship_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ship Length (Meter)'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Built Year'),
        ),
    ]
