# Generated by Django 3.0.5 on 2020-05-30 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewdatabd', '0005_auto_20200530_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='district',
            field=models.ForeignKey(blank=True, default=65, null=True, on_delete=django.db.models.deletion.CASCADE, to='crewdatabd.District'),
        ),
        migrations.AlterField(
            model_name='companie',
            name='thana',
            field=models.ForeignKey(blank=True, default=1257, null=True, on_delete=django.db.models.deletion.CASCADE, to='crewdatabd.Thana'),
        ),
    ]
