# Generated by Django 3.0.5 on 2020-05-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdatabd', '0006_auto_20200530_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='association_website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
