# Generated by Django 3.0.5 on 2020-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdatabd', '0007_association_association_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companie',
            name='cc_address',
        ),
        migrations.RemoveField(
            model_name='companie',
            name='cc_contact_no',
        ),
        migrations.RemoveField(
            model_name='companie',
            name='cc_contact_person',
        ),
        migrations.RemoveField(
            model_name='companie',
            name='cc_email',
        ),
        migrations.RemoveField(
            model_name='companie',
            name='charter_company',
        ),
        migrations.AddField(
            model_name='companie',
            name='company_website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
